name: API

on:
  pull_request:
    paths:
      - 'packages/api/**'
  push:
    paths:
      - 'packages/api/**'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn
      - run: yarn workspace @poc/api lint
